-d C:\Users\PC\Documents\GOWINFPGA\PF\impl\gwsynthesis\PF.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\PC\Documents\GOWINFPGA\PF\src\PF.cst
-cfg C:\Users\PC\Documents\GOWINFPGA\PF\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
